# Generated by Django 4.2.5 on 2023-09-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
