# Generated by Django 4.2.5 on 2023-09-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_detection_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.position'),
            preserve_default=False,
        ),
    ]
