# Generated by Django 4.2.5 on 2023-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_detection_detector_analysis_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='wikipedia_description',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikidata_url',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikimedia_photo_urls',
            field=models.URLField(blank=True, max_length=1033),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikimedia_url',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
