# Data meta

[position]
# A position already loaded in the database
name = "Earth Trust"
uuid = "637e78cc56974a808d108d60f70676f8"

[analysis]
# An analysis already loaded in the database
name = "BirdNet"
uuid = "27df0a2e-f4cb-499f-98ec-a2e05a63e25e"

[detector]
# A detector already loaded in the database
name = "Audio"
uuid = "672052b23847415384e8a9813932ebed"

[indexer]
# The code to run this folder of stuff against
class_name = "BirdNet"
file_types = "csv"


title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

# Indentation (tabs and/or spaces) is allowed but not required
[servers.alpha]
ip = "10.0.0.1"
dc = "eqdc10"

[servers.beta]
ip = "10.0.0.2"
dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
    "alpha",
    "omega"
]